# Site settings
title: "Việc Tốt"
url-title: "Việc Tốt"
description: "Bí quyết nội trợ."
paginate: 100
url: "https://histesh.site"
permalink: /:year/:month/:title/
include: ['_headers']
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
